# Generated by Django 5.0.4 on 2024-04-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='joke',
            field=models.CharField(default='Joke', max_length=1024, verbose_name='joke'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='long_name',
            field=models.CharField(default='Joke', max_length=1024, verbose_name='long name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='punchline',
            field=models.CharField(default='Joke', max_length=256, verbose_name='punchline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
    ]
