# Generated by Django 5.0.4 on 2024-04-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_joke_product_long_name_product_punchline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_name',
        ),
    ]
